// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA_fIeI3MCWJksopZHTQyEedMjLID06mw',
    appId: '1:938105818460:web:f8060c19ff149b02320599',
    messagingSenderId: '938105818460',
    projectId: 'test-eef04',
    authDomain: 'test-eef04.firebaseapp.com',
    storageBucket: 'test-eef04.appspot.com',
    measurementId: 'G-N8RLW4PRHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO4iuxUikyR8mS8W6lVjoXjs5YXYyuH24',
    appId: '1:938105818460:android:4f4a5e5f6a33676a320599',
    messagingSenderId: '938105818460',
    projectId: 'test-eef04',
    storageBucket: 'test-eef04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM4GoDK_LcGsWXgOwEBuOpdYVvJ37XYX4',
    appId: '1:938105818460:ios:5bcedfd41dfdc5a5320599',
    messagingSenderId: '938105818460',
    projectId: 'test-eef04',
    storageBucket: 'test-eef04.appspot.com',
    iosBundleId: 'com.example.restaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM4GoDK_LcGsWXgOwEBuOpdYVvJ37XYX4',
    appId: '1:938105818460:ios:5bcedfd41dfdc5a5320599',
    messagingSenderId: '938105818460',
    projectId: 'test-eef04',
    storageBucket: 'test-eef04.appspot.com',
    iosBundleId: 'com.example.restaurant',
  );
}
